version: '3'
services:
  app:
    build: .
    ports:
      - '8082:8082'
    environment:
      - TZ=Asia/Almaty
    depends_on:
      - psql
      - redis
    restart: unless-stopped

  psql:
    image: postgres:14.1-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: sber-invest-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PostgresInvest2022
      PGDATA: /data/postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - pg-data:/var/lib/postgresql/data
    ports:
      - '5434:5434'
    restart: unless-stopped

volumes:
  pg-data:
    driver: local
  cache:
    driver: local
